makeBoard/makeBoard/urls.py
from django.contrib import admin
from django.urls import path,include #추가
from django.conf import settings
from boards1 import views
from django.conf.urls.static import static



urlpatterns = [
    path('',views.home, name='home'),
    path('new_topic/',views.new_topic,name='new_topic'),#게시글 작성 페이지 url 추가
    path('summernote/', include('django_summernote.urls')),#summernote url 추가
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

makeBoard/boards1/models.py
from django.db import models
# Create your models here.


from django.contrib.auth.models import User
#http 상태를 나타내기 위한 장고 모듈

from django_summernote.fields import SummernoteTextField



class Topic(models.Model):
    content= SummernoteTextField(null=True)
    subject = models.CharField(max_length=255)
    last_updated =  models.DateField(auto_now_add=True, null=True)
    writter = models.ForeignKey(User, related_name='topics',on_delete=models.CASCADE, null=True)    

class Reply(models.Model):
    message = models.TextField(max_length=5000)
    created_at = models.DateTimeField(auto_now_add=True)
    created_by= models.ForeignKey(User, null=True, related_name='posts',on_delete=models.CASCADE)
    updated_at = models.DateField(null = True)
    updated_by=  models.ForeignKey(User,null=True,related_name='+',on_delete=models.CASCADE)

makeBoard/boards1/forms.py
from django import forms
from .models import Topic

from django_summernote.fields import SummernoteTextFormField, SummernoteTextField



class SummerForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = (
            'content',
        )

makeBoard/boards1/views.py
#사용자정의
from django.contrib.auth.models import User
#장고의 사용자 모듈


# 장고의 view를 html문법으로 바꾸기 위한 렌더링모듈 과 new_topic view가 home으로 돌아가기 위한 redirect모듈
from django.shortcuts import render, redirect


from  .models import Topic, Reply
# 모델의 클래스명

from django.http import HttpResponse

from .forms import SummerForm
from django.contrib.auth.models import User


#form.py를 불러옴
#from .forms import RichForm


# 추가하기
def home(request):
 
    topics = Topic.objects.all()   #models의 Topic 개체 생성
    return render(request,'home.html')
 
def new_topic(request):
    form = SummerForm()
    topics = Topic.objects.all()    
    if request.method =='POST':
        subject = request.POST['subject']
        user = User.objects.first()

        topic = Topic.objects.create(
            subject=subject,         
            user=user,
        )

        post = Reply.objects.create(
            # message=message, 삭제
            created_by=user

        )

        return redirect('home')
  
       
    
    return render(request,'new_topic.html',{'form': SummerForm()})

makeBoard/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>DjangoBoard</title>
    <link href="https://fonts.googleapis.com/css2?family=Nanum+Gothic:wght@700&display=swap" rel="stylesheet">


    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    {{ form.media }}

</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-info">
        <div class="container">
            <a class="navbar-brand" href="{% url 'home' %}">장고 게시판</a>

        </div>
    </nav>

    <!-- 여기에 컨텐츠들을 계속 넣습니다.유지보수를 위해서 -->
    <div class="container">
        {% block content %}
        <!-- 이제 이부분에 content라는 이름으로 이어받아서 작성할수 있습니다. -->
        {% endblock %}
    </div>
</body>


</html>

makeBoard/templates/home.html
{% extends  'base.html' %}
     {% block content %}
        <table class="table">
            <thead class="">
                <tr> 
                    <th>작성자</th>
                    <th>제목</th>
                    <th>조회수</th>
                    <th>댓글수</th>
                    <th>작성일자</th>
                </tr>

            </thead>

            <tbody>
                {% for topic in topics %}
                <tr>
                    <td>{{topic.writter.username }}</td>
                    <td>{{topic.subject }}</td>
                    <td>0</td>
                    <td>0</td>
                    <td>{{topic.last_updated}}</td>
                </tr>
                {% endfor %}

            </tbody>
          
        </table>

        
         <!-- add creating posting button  게시글 버튼-->
    
         <div class="mb-4">
            <a href="{% url 'new_topic' %}" class="btn btn-info"><b>글 작성</b></a>
        </div> 


  {% endblock %}

makeBoard/templates/new_topic.html
{% extends 'base.html' %}

{% block content %}
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}

    <!-- testtest1 -->
    <!-- writting title -->
    <div class="form-group">
        <label for="id_subject"> 제목 </label>
        <input type="text" class="form-control" id="id_subject" name="subject">

    </div>

    <div class="form-group">
        <label for="id_message">내용 </label>
    </div>

    {{form.content}}
    <button type="submit" class="btn btn-info">등록</button>
     
    <button class= "btn btn-info" onclick="location.href='{% url 'home' %}'"> 취소</button>     




</form>    
       
    



{% endblock %}